backend:
  name: github
  repo: bushrafajr-1519/the-living-guide
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    files:
      - name: "first-article"
        label: "First Article"
        file: "content/first-article.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Category", name: "category", widget: "string" }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Body", name: "body", widget: "markdown" }