backend:
  name: github
  repo: bushrafajr-1519/the-living-guide
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    extension: "html"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }